SMS/urls.py
from django.urls import path, include, re_path
from apps.front import urls as fulrs
from apps.cms import urls as curls
from django.views.static import serve
from . import settings

urlpatterns = [
    path('', include(fulrs, namespace='front')),
    path('cms/', include(curls, namespace='cms')),
    path('ajax/', include(curls, namespace='ajax')),
    re_path(r'media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),

]

apps/front/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
from apps.user.student_views import LoginView, RegisterView, LogOutView, ChangeInfoView1,ChangeLogo,ChangeInfoView,Telephone_home,Telephone_login,Telephone_send,Pachong,Pachong1
# from apps.user.student_views import get_identifyCode
from apps.user import student_views

app_name = 'front'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('change_info/', ChangeInfoView.as_view(), name='change_info'),
    path('change_info1/', ChangeInfoView1.as_view(), name='change_info1'),
    path('change_logo/', ChangeLogo.as_view(), name='change_logo'),
    path('telephone_home/', Telephone_home.as_view(), name='telephone_home'),
    path('telephone_login/', Telephone_login.as_view(), name='telephone_login'),
    path('telephone_send/', Telephone_send.as_view(), name='telephone_send'),
    path('pachong/', Pachong.as_view(), name='pachong'),
    path('pachong1/', Pachong1.as_view(), name='pachong1'),
    path('home_view/', views.HomeView.as_view(), name='home_view'),
    path('renren/', views.RenrenView.as_view(), name='renren'),
    path('qzone/', views.QzoneView.as_view(), name='qzone'),
]

apps/front/models.py
from django.db import models
from django.core import validators
from tools.my_validators import userNameMaxLengthValidator, userNameMinLengthValidator, telephoneValidator
# Create your models here.

apps/front/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import View
from django.http import HttpResponse
from tools.set_context_info import get_context_from_request_by_context
from tools.my_decorator import student_login_require, login_out, info_filtration
from tools.captcha import Captcha
from io import BytesIO
import json
from apps.front.renren import renren
from apps.front.qqzone import Qzone
# Create your views here.


class IndexView(View):
    # @student_login_require('front:login')
    def get(self, request):
        """
        主页get访问
        :param request:HttpRequest对象
        :return: 返回HttpResponse对象获取，render()
        """
        context = {}
        return render(request, 'front/index.html', context=context)

    def http_method_not_allowed(self,request):
        return HttpResponse('403')


class ShowView(View):
    @student_login_require('front:login')
    def get(self, request):
        """
        show页面get访问
        :param request:HttpRequest对象
        :return: 返回HttpResponse对象获取，render()
        """
        context = {}
        return render(request, 'front/index.html', context=context)

    def http_method_not_allowed(self):
        return HttpResponse('403')
class HomeView(View):
    @student_login_require('homepage')
    @info_filtration
    def get(self, request):
        """
        show页面get访问
        :param request:HttpRequest对象
        :return: 返回HttpResponse对象获取，render()
        """
        context = {}
        context = get_context_from_request_by_context(request, context)
        return render(request, 'profile-page.html', context=context)

    def http_method_not_allowed(self):
        return HttpResponse('403')

class MoreView(View):
    @student_login_require('')
    @info_filtration
    def get(self, request):
        """
        show页面get访问
        :param request:HttpRequest对象
        :return: 返回HttpResponse对象获取，render()
        """

        context = {}
        context = get_context_from_request_by_context(request, context)
        return render(request, '', context=context)

    def http_method_not_allowed(self):
        return HttpResponse('403')


class RenrenView(View):
    def get(self, request):
        """
        show页面get访问
        :param request:HttpRequest对象
        :return: 返回HttpResponse对象获取，render()
        """
        opener = renren.get_opener()
        renren.login_renren(opener)
        renren.visit_profile(opener)
        return render(request, 'renren.html')

    def http_method_not_allowed(self):
        return HttpResponse('403')

class QzoneView(View):
    def get(self, request):
        """
        show页面get访问
        :param request:HttpRequest对象
        :return: 返回HttpResponse对象获取，render()
        """
        opener = Qzone.get_opener()
        Qzone.login_qzone(opener)
        Qzone.visit_profile(opener)
        return render(request, 'qzone.html')

    def http_method_not_allowed(self):
        return HttpResponse('403')

apps/front/templates/front/change_info.html
{% load staticfiles%}
{% load user_tags %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}

{% endblock %}</title>

        <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="../../../../static/assets1/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="../../../../static/assets1/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="../../../../static/assets1/css/form-elements.css">
        <link rel="stylesheet" href="../../../../static/assets1/css/style.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="../../../../static/assets1/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../../../../static/assets1/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../../../../static/assets1/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../../../../static/assets1/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../../../../static/assets1/ico/apple-touch-icon-57-precomposed.png">

    </head>

    <body background="../../../../static/assets1/img/b.jpg">
        {% block script %}
        <script type="text/javascript">
            {% if error_info %}
                xtalert.alertError('{{ error_info }}')
            {% endif %}
            {% if info %}
                 xtalert.alertInfo('{{ info }}')
            {% endif %}
            {% if success_info %}
                 xtalert.alertSuccessToast('{{ success_info }}！');
            {% endif %}
        </script>
        {% endblock %}

		<!-- Top menu -->
		<nav class="navbar navbar-inverse navbar-no-bg" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="">Bootstrap Flat Registration Form Template</a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="top-navbar-1">
					<ul class="nav navbar-nav navbar-right">
{#						<li>#}
{#							<span class="li-text">#}
{#								点击我回到个人中心#}
{#							</span> #}
							<a href="{% url 'front:change_info1' %}"><strong>个人中心</strong></a>
                            <span class="li-text">
								||
							</span>
							<a href="{% url 'front:index' %}"><strong color="pink">主页</strong></a>
							<span class="li-text">
								|| 这里提供一些其它登录的方式:
							</span>
							<span class="li-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-envelope"></i></a>
								<a href="#"><i class="fa fa-skype"></i></a>
							</span>
						</li>
					</ul>
				</div>
			</div>
		</nav>

        <!-- Top content -->
        <div class="top-content">

            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-7 text">
{#                            <div class="top-big-link">#}
{#                            	<a class="btn btn-link-1" href="{% url 'front:index' %}">回到主页</a>#}
{#                            	<a class="btn btn-link-2" href=""></a>#}
{#                            </div>#}
                        </div>
                        <div class="col-sm-5 form-box">
                        	<div class="form-top">
                        		<div class="form-top-left">
                        			<h3>Change yourself now</h3>
                            		<p>Fill in the form below to get instant access:</p>
                        		</div>
                        		<div class="form-top-right">
                        			<i class="fa fa-pencil"></i>
                        		</div>
                        		<div class="form-top-divider"></div>
                            </div>
                            <div class="form-bottom">
			                    <form role="form" action="{% url 'front:change_info' %}" method="post" class="registration-form">
                                    {% csrf_token %}
{#			                    	<div class="form-group">#}
{#			                    		<label class="sr-only" for="form-first-name">用户名</label>#}
{#			                        	<input type="text" name="name" placeholder="用户名" class="form-first-name form-control" id="form-first-name">#}
{#			                        </div>#}
{#                                    <img src="../static/images/{{ user.icon }}" alt="头像" style="width: 200px;height: 200px">#}
{#                                    <input type="submit" value="更改头像">#}
{#                                    <div class="form-group">#}
{#			                        	<img src="../media/images/{{ user.icon }}" alt="头像" style="width: 200px;height: 200px">#}
{#                                        <input type="file" name="icon">#}
{#                                        <input type="submit" value="更改头像">#}
{#			                        </div>#}
{#                                    <input type="submit" value="上传">#}
			                        <div class="form-group">
			                        	<label class="sr-only" for="form-last-name">手机号</label>
			                        	<input type="text" name="telephone" placeholder="手机号:{{ user.telephone }}" class="form-last-name form-control" id="form-last-name">
			                        </div>
			                        <div class="form-group">
			                        	<label class="sr-only" for="form-email">Email</label>
			                        	<input type="email" name="email" placeholder="Email:{{ user.email }}" class="form-email form-control" id="form-email">
		                        </div>
{#			                        <div class="form-group">#}
{#			                        	<label class="sr-only" for="form-about-yourself">个性签名</label>#}
{#			                        	<textarea name="form-about-yourself" placeholder="个性签名"#}
{#			                        				class="form-about-yourself form-control" id="form-about-yourself"></textarea>#}
{#			                        </div>#}
			                        <button type="submit" class="btn">立即修改</button>
			                    </form>
		                    </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>


        <!-- Javascript -->
        <script src="../../../../static/assets1/js/jquery-1.11.1.min.js"></script>
        <script src="../../../../static/assets1/bootstrap/js/bootstrap.min.js"></script>
        <script src="../../../../static/assets1/js/jquery.backstretch.min.js"></script>
        <script src="../../../../static/assets1/js/retina-1.1.0.min.js"></script>
        <script src="../../../../static/assets1/js/scripts.js"></script>

        <!--[if lt IE 10]>
            <script src="../../../../static/assets1/js/placeholder.js"></script>
        <![endif]-->

    </body>

</html>

apps/front/templates/front/change_logo.html
{% load staticfiles%}
{% load user_tags %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>修改头像</title>
<link href="../../../../static/Wopop_files/style_log.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="../../../../static/Wopop_files/style.css">
<link rel="stylesheet" type="text/css" href="../../../../static/Wopop_files/userpanel.css">
<link rel="stylesheet" type="text/css" href="../../../../static/Wopop_files/jquery.ui.all.css">

</head>

<body class="login" mycollectionplug="bind">
        {% block script %}
        <script type="text/javascript">
            {% if error_info %}
                xtalert.alertError('{{ error_info }}')
            {% endif %}
            {% if info %}
                 xtalert.alertInfo('{{ info }}')
            {% endif %}
            {% if success_info %}
                 xtalert.alertSuccessToast('{{ success_info }}！');
            {% endif %}
        </script>
        {% endblock %}

    <div class="login_m">
    <div class="login_logo"><img src="../../../../static/Wopop_files/logo.png" width="196" height="46"></div>
        <div class="login_boder">

            <div class="login_padding" id="login_model">
                <form action="{% url 'front:change_logo' %}" enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="rem_sub">
                        <img src="../media/{{ user.icon }}" alt="头像" style="width: 200px;height: 200px">
                        <input type="file" name="icon">
{#                        <input type="submit" value="更改头像">#}
                        <label>
                          <input type="submit" class="sub_button" name="button" id="button" value="上传头像" style="opacity: 0.7;">
                        </label>
                    </div>
                </form>

            </div>

        </div>
        <div class="collapse navbar-collapse" id="top-navbar-1">
					<ul class="nav navbar-nav navbar-right">
                            <span class="li-text">
								返回：
							</span>
							<a href="{% url 'front:change_info1' %}"><strong>个人中心</strong></a>
                            <span class="li-text">
								||
							</span>
							<a href="{% url 'front:index' %}"><strong color="pink">主页</strong></a>
						</li>
					</ul>
				</div>
			</div>
    </div>


</body></html>

apps/front/templates/front/index.html
{% extends 'base.html' %}
{% block title %}
主页
{% endblock %}
{% block index_navbar_class %}
    class="active"
{% endblock %}

apps/front/templates/front/index1.html
{% load staticfiles%}
{% load user_tags %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}
    index
{% endblock %}</title>
	<link rel="stylesheet" href="../../../../static/CSS/auth.css">
    <!-- 加载动态 -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="../../../../static/CSS/font-awesome.min.css">
    <link rel="stylesheet" href="../../../../static/CSS/bootstrap.min.css">

    <link rel="stylesheet" href="../../../../static/CSS/demo.css" />
    <link rel="stylesheet" href="../../../../static/CSS/templatemo-style.css">

    <script type="text/javascript" src="../../../../static/JS/modernizr.custom.86080.js"></script>
</head>

<body>
{% block script %}
        <script type="text/javascript">
            {% if error_info %}
                xtalert.alertError('{{ error_info }}')
            {% endif %}
            {% if info %}
                 xtalert.alertInfo('{{ info }}')
            {% endif %}
            {% if success_info %}
                 xtalert.alertSuccessToast('{{ success_info }}！');
            {% endif %}
        </script>
        {% endblock %}
    {% block navbar %}
        <div id="particles-js"></div>

			<ul class="cb-slideshow">
	            <li></li>
	            <li></li>
	            <li></li>
	        </ul>

			<div class="container-fluid">

				<div class="row cb-slideshow-text-container ">
					<div class= "tm-content col-xl-6 col-sm-8 col-xs-8 ml-auto section">
    <div class="lowin">
		<div class="lowin-brand">
			<img src="../../../../static/images/kodinger.jpg" alt="logo">
		</div>
		<div class="lowin-wrapper">
			<div class="lowin-box lowin-login">
				<div class="lowin-box-inner">
					<form action="{% url 'front:login' %}" method="post">
                    {% csrf_token %}
						<p>会员登录</p>
						<div class="lowin-group">
							<label>用户名<a href="#" class="login-back-link">登录？</a></label>
							<input type="text" autocomplete="name" name="name" class="lowin-input">
						</div>
						<div class="lowin-group password-group">
							<label>密码 <a href="" class="forgot-link"><span><a href="{% url 'front:telephone_home' %}">忘记密码？</a></span></a></label>
							<input type="password" name="password" autocomplete="current-password" class="lowin-input">
						</div>
						<button class="lowin-btn login-btn">
                            立即登录
						</button>

						<div class="text-foot">
							没有账号？<a href="" class="register-link">注册</a><br>
                           身份不同？<a href="{% url 'cms:login' %}">管理员登录</a>
						</div>
					</form>
				</div>
			</div>

			<div class="lowin-box lowin-register">
				<div class="lowin-box-inner">
					<form action="{% url 'front:register' %}" method="post">
                        {% csrf_token %}
						<p>Let's create your account</p>
						<div class="lowin-group">
							<label>用户名</label>
							<input type="text" name="name" autocomplete="username" class="lowin-input">
						</div>
                        <div class="lowin-group">
							<label>手机号</label>
							<input type="text" name="telephone" autocomplete="telephone" class="lowin-input">
						</div>
                        <div class="lowin-group">
							<label>邮箱</label>
							<input type="email" name="email" autocomplete="email" class="lowin-input">
						</div>
						<div class="lowin-group">
							<label>密码</label>
							<input type="password" name="pwd1" autocomplete="current-password" class="lowin-input">
						</div>
						<div class="lowin-group">
							<label>确认密码</label>
							<input type="password" name="pwd2" autocomplete="current-password" class="lowin-input">
						</div>
						<button class="lowin-btn">
							注册
						</button>

						<div class="text-foot">
							已经有账号? <a href="" class="login-link">登录</a>
						</div>
					</form>
				</div>
			</div>
		</div>

		<footer class="lowin-footer">

		</footer>
	</div>

					</div>
				</div>
			</div>
    {% endblock %}

	<script src="../../../../static/JS/auth.js"></script>
	<script>
		Auth.init({
			login_url: '#login',
			forgot_url: '#forgot'
		});
	</script>
    <script type="text/javascript" src="../../../../static/JS/particles.js"></script>
	<script type="text/javascript" src="../../../../static/JS/app.js"></script>
</body>
</html>

apps/front/templates/front/telephone.html
{% load staticfiles%}
{% load user_tags %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}
    index
{% endblock %}</title>
	<link rel="stylesheet" href="../../../../static/CSS/auth.css">
    <!-- 加载动态 -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="../../../../static/CSS/font-awesome.min.css">
    <link rel="stylesheet" href="../../../../static/CSS/bootstrap.min.css">

    <link rel="stylesheet" href="../../../../static/CSS/demo.css" />
    <link rel="stylesheet" href="../../../../static/CSS/templatemo-style.css">

    <script type="text/javascript" src="../../../../static/JS/modernizr.custom.86080.js"></script>
</head>

<body>
{% block script %}
        <script type="text/javascript">
            {% if error_info %}
                xtalert.alertError('{{ error_info }}')
            {% endif %}
            {% if info %}
                 xtalert.alertInfo('{{ info }}')
            {% endif %}
            {% if success_info %}
                 xtalert.alertSuccessToast('{{ success_info }}！');
            {% endif %}
        </script>
        {% endblock %}
    {% block navbar %}
        <div id="particles-js"></div>

			<ul class="cb-slideshow">
	            <li></li>
	            <li></li>
	            <li></li>
	        </ul>

			<div class="container-fluid">

				<div class="row cb-slideshow-text-container ">
					<div class= "tm-content col-xl-6 col-sm-8 col-xs-8 ml-auto section">
    <div class="lowin">
		<div class="lowin-brand">
			<img src="../../../../static/images/kodinger.jpg" alt="logo">
		</div>
		<div class="lowin-wrapper">
			<div class="lowin-box lowin-login">
				<div class="lowin-box-inner">
					<form action="{% url 'front:telephone_send' %}" method="post">
                    {% csrf_token %}
						<p>Send telephone message</p>
						<div class="lowin-group">
							<label>手机号<a href="#" class="login-back-link">登录？</a></label>
                            <input type="text" name="phone" id="phone" autocomplete="current-password" class="lowin-input">
						</div>
						<button class="lowin-btn login-btn">
                            发送验证码
                        </button>

						<div class="text-foot">
							返回登录页？<a href="{% url 'front:login' %}">返回</a>
						</div>
					</form>
				</div>
			</div>
{##}
{#			<div class="lowin-box lowin-register">#}
{#				<div class="lowin-box-inner">#}
{#					<form action="{% url 'front:register' %}" method="post">#}
{#                        {% csrf_token %}#}
{#						<p>Let's create your account</p>#}
{#						<div class="lowin-group">#}
{#							<label>用户名</label>#}
{#							<input type="text" name="name" autocomplete="username" class="lowin-input">#}
{#						</div>#}
{#                        <div class="lowin-group">#}
{#							<label>手机号</label>#}
{#							<input type="text" name="telephone" autocomplete="telephone" class="lowin-input">#}
{#						</div>#}
{#                        <div class="lowin-group">#}
{#							<label>邮箱</label>#}
{#							<input type="email" name="email" autocomplete="email" class="lowin-input">#}
{#						</div>#}
{#						<div class="lowin-group">#}
{#							<label>密码</label>#}
{#							<input type="password" name="pwd1" autocomplete="current-password" class="lowin-input">#}
{#						</div>#}
{#						<div class="lowin-group">#}
{#							<label>确认密码</label>#}
{#							<input type="password" name="pwd2" autocomplete="current-password" class="lowin-input">#}
{#						</div>#}
{#						<button class="lowin-btn">#}
{#							注册#}
{#						</button>#}
{##}
{#						<div class="text-foot">#}
{#							已经有账号? <a href="" class="login-link">登录</a>#}
{#						</div>#}
{#					</form>#}
{#				</div>#}
{#			</div>#}
		</div>

		<footer class="lowin-footer">

		</footer>
	</div>

					</div>
				</div>
			</div>
    {% endblock %}

	<script src="../../../../static/JS/auth.js"></script>
	<script>
		Auth.init({
			login_url: '#login',
			forgot_url: '#forgot'
		});
	</script>
    <script type="text/javascript" src="../../../../static/JS/particles.js"></script>
	<script type="text/javascript" src="../../../../static/JS/app.js"></script>
</body>
</html>

apps/front/templates/front/telephone_login.html
{% load staticfiles%}
{% load user_tags %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}
    index
{% endblock %}</title>
	<link rel="stylesheet" href="../../../../static/CSS/auth.css">
    <!-- 加载动态 -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="../../../../static/CSS/font-awesome.min.css">
    <link rel="stylesheet" href="../../../../static/CSS/bootstrap.min.css">

    <link rel="stylesheet" href="../../../../static/CSS/demo.css" />
    <link rel="stylesheet" href="../../../../static/CSS/templatemo-style.css">

    <script type="text/javascript" src="../../../../static/JS/modernizr.custom.86080.js"></script>
</head>

<body>
{% block script %}
        <script type="text/javascript">
            {% if error_info %}
                xtalert.alertError('{{ error_info }}')
            {% endif %}
            {% if info %}
                 xtalert.alertInfo('{{ info }}')
            {% endif %}
            {% if success_info %}
                 xtalert.alertSuccessToast('{{ success_info }}！');
            {% endif %}
        </script>
        {% endblock %}
    {% block navbar %}
        <div id="particles-js"></div>

			<ul class="cb-slideshow">
	            <li></li>
	            <li></li>
	            <li></li>
	        </ul>

			<div class="container-fluid">

				<div class="row cb-slideshow-text-container ">
					<div class= "tm-content col-xl-6 col-sm-8 col-xs-8 ml-auto section">
    <div class="lowin">
		<div class="lowin-brand">
			<img src="../../../../static/images/kodinger.jpg" alt="logo">
		</div>
		<div class="lowin-wrapper">
			<div class="lowin-box lowin-login">
				<div class="lowin-box-inner">
					<form action="{% url 'front:telephone_login' %}" method="post">
                    {% csrf_token %}
						<p>手机登录</p>
						<div class="lowin-group">
							<label>手机号<a href="#" class="login-back-link">登录？</a></label>
                            <input type="text" name="phone" id="phone" autocomplete="current-password" class="lowin-input">
						</div>
						<div class="lowin-group password-group">
							<label>验证码</label>
							<input type="text" autocomplete="mycode" name="mycode" class="lowin-input">
						</div>
						<button class="lowin-btn login-btn">
                            立即登录
						</button>

						<div class="text-foot">
							返回登录页? <a href="{% url 'front:login' %}" class="login-link">返回</a>
						</div>
					</form>
				</div>
			</div>
{#			<div class="lowin-box lowin-register">#}
{#				<div class="lowin-box-inner">#}
{#					<form action="{% url 'front:register' %}" method="post">#}
{#                        {% csrf_token %}#}
{#						<p>Let's create your account</p>#}
{#						<div class="lowin-group">#}
{#							<label>用户名</label>#}
{#							<input type="text" name="name" autocomplete="username" class="lowin-input">#}
{#						</div>#}
{#                        <div class="lowin-group">#}
{#							<label>手机号</label>#}
{#							<input type="text" name="telephone" autocomplete="telephone" class="lowin-input">#}
{#						</div>#}
{#                        <div class="lowin-group">#}
{#							<label>邮箱</label>#}
{#							<input type="email" name="email" autocomplete="email" class="lowin-input">#}
{#						</div>#}
{#						<div class="lowin-group">#}
{#							<label>密码</label>#}
{#							<input type="password" name="pwd1" autocomplete="current-password" class="lowin-input">#}
{#						</div>#}
{#						<div class="lowin-group">#}
{#							<label>确认密码</label>#}
{#							<input type="password" name="pwd2" autocomplete="current-password" class="lowin-input">#}
{#						</div>#}
{#						<button class="lowin-btn">#}
{#							注册#}
{#						</button>#}
{##}
{#						<div class="text-foot">#}
{#							已经有账号? <a href="" class="login-link">登录</a>#}
{#						</div>#}
{#					</form>#}
{#				</div>#}
{#			</div>#}
		</div>

		<footer class="lowin-footer">

		</footer>
	</div>

					</div>
				</div>
			</div>
    {% endblock %}

	<script src="../../../../static/JS/auth.js"></script>
	<script>
		Auth.init({
			login_url: '#login',
			forgot_url: '#forgot'
		});
	</script>
    <script type="text/javascript" src="../../../../static/JS/particles.js"></script>
	<script type="text/javascript" src="../../../../static/JS/app.js"></script>
</body>
</html>