SMS/urls.py
from django.urls import path, include, re_path
from apps.front import urls as fulrs
from apps.cms import urls as curls
from django.views.static import serve
from . import settings

urlpatterns = [
    path('', include(fulrs, namespace='front')),
    path('cms/', include(curls, namespace='cms')),
    path('ajax/', include(curls, namespace='ajax')),
    re_path(r'media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),

]

apps/cms/urls.py
from django.urls import path

from . import views
from apps.user.teacher_views import Member_warn, LoginView, RegisterView, LogOutView, ChangeInfoView,ChangeInfoView1,ChangeLogo,Manager_home,Member_list

app_name = 'cms'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('change_info/', ChangeInfoView.as_view(), name='change_info'),
    path('change_info1/', ChangeInfoView1.as_view(), name='change_info1'),
    path('change_logo/', ChangeLogo.as_view(), name='change_logo'),
    path('manager_home/', Manager_home.as_view(), name='manager_home'),
    path('member_list/', Member_list.as_view(), name='member_list'),
    path('member_warn/', Member_warn.as_view(), name='member_warn'),
    # path('member_warn/',views.Manager_dalete, name='member_warn'),
]

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import View
from django.http import HttpResponse
from tools.set_context_info import get_context_from_request_by_context
from tools.my_decorator import teacher_login_require, login_out, info_filtration

# Create your views here.


class IndexView(View):
    @teacher_login_require('cms:login')
    @info_filtration  # 该装饰器用于获取那些被重定向到主页前，往session中存入的信息，这些信息将会在主页进行展示
    def get(self, request):
        """
        主页get访问
        :param request:HttpRequest对象
        :return: 返回HttpResponse对象获取，render()
        """
        context = {}
        context = get_context_from_request_by_context(request, context)
        return render(request, 'cms/index.html', context=context)

    def http_method_not_allowed(self,request):
        return HttpResponse('403')


class ShowView(View):
    @teacher_login_require('cms:login')
    @info_filtration  # 该装饰器用于获取那些被重定向到主页前，往session中存入的信息，这些信息将会在主页进行展示，该拦截器应配合get_context_from_request_by_context()
    def get(self, request):
        """
        show页面get访问
        :param request:HttpRequest对象
        :return: 返回HttpResponse对象获取，render()
        """
        context = {}
        context = get_context_from_request_by_context(request, context)
        return render(request, 'cms/index.html', context=context)

    def http_method_not_allowed(self,request):
        return HttpResponse('403')

apps/cms/templates/cms/change_info.html
{#{% extends 'base.html' %}#}
{#{% block title %}#}
{#    信息修改#}
{#{% endblock %}#}
{#{% block content %}#}
{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_ul }}#}
{#        <input type="submit" value="提交">#}
{#    </form>#}
{#{% endblock %}#}
{% load staticfiles%}
{% load user_tags %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}
修改信息
{% endblock %}</title>

        <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="../../../../static/assets1/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="../../../../static/assets1/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="../../../../static/assets1/css/form-elements.css">
        <link rel="stylesheet" href="../../../../static/assets1/css/style.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="../../../../static/assets1/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../../../../static/assets1/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../../../../static/assets1/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../../../../static/assets1/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../../../../static/assets1/ico/apple-touch-icon-57-precomposed.png">

    </head>

    <body background="../../../../static/assets1/img/b.jpg">
{#    <body>#}
        {% block script %}
        <script type="text/javascript">
            {% if error_info %}
                xtalert.alertError('{{ error_info }}')
            {% endif %}
            {% if info %}
                 xtalert.alertInfo('{{ info }}')
            {% endif %}
            {% if success_info %}
                 xtalert.alertSuccessToast('{{ success_info }}！');
            {% endif %}
        </script>
        {% endblock %}

		<!-- Top menu -->
		<nav class="navbar navbar-inverse navbar-no-bg" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="">Bootstrap Flat Registration Form Template</a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="top-navbar-1">
					<ul class="nav navbar-nav navbar-right">
{#						<li>#}
{#							<span class="li-text">#}
{#								点击我回到个人中心#}
{#							</span> #}
							<a href="{% url 'cms:change_info1' %}"><strong>个人中心</strong></a>
                            <span class="li-text">
								||
							</span>
							<a href="{% url 'cms:index' %}"><strong color="pink">主页</strong></a>
							<span class="li-text">
								|| 这里提供一些其它登录的方式:
							</span>
							<span class="li-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-envelope"></i></a>
								<a href="#"><i class="fa fa-skype"></i></a>
							</span>
						</li>
					</ul>
				</div>
			</div>
		</nav>

        <!-- Top content -->
        <div class="top-content">

            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-7 text">
{#                            <div class="top-big-link">#}
{#                            	<a class="btn btn-link-1" href="{% url 'front:index' %}">回到主页</a>#}
{#                            	<a class="btn btn-link-2" href=""></a>#}
{#                            </div>#}
                        </div>
                        <div class="col-sm-5 form-box">
                        	<div class="form-top">
                        		<div class="form-top-left">
                        			<h3>Change yourself now</h3>
                            		<p>Fill in the form below to get instant access:</p>
                        		</div>
                        		<div class="form-top-right">
                        			<i class="fa fa-pencil"></i>
                        		</div>
                        		<div class="form-top-divider"></div>
                            </div>
                            <div class="form-bottom">
			                    <form role="form" action="{% url 'cms:change_info' %}" method="post" class="registration-form">
                                    {% csrf_token %}
{#			                    	<div class="form-group">#}
{#			                    		<label class="sr-only" for="form-first-name">用户名</label>#}
{#			                        	<input type="text" name="name" placeholder="用户名" class="form-first-name form-control" id="form-first-name">#}
{#			                        </div>#}
{#                                    <img src="../static/images/{{ user.icon }}" alt="头像" style="width: 200px;height: 200px">#}
{#                                    <input type="submit" value="更改头像">#}
{#                                    <div class="form-group">#}
{#			                        	<img src="../media/images/{{ user.icon }}" alt="头像" style="width: 200px;height: 200px">#}
{#                                        <input type="file" name="icon">#}
{#                                        <input type="submit" value="更改头像">#}
{#			                        </div>#}
{#                                    <input type="submit" value="上传">#}
			                        <div class="form-group">
			                        	<label class="sr-only" for="form-last-name">手机号</label>
			                        	<input type="text" name="telephone" placeholder="手机号:{{ user.telephone }}" class="form-last-name form-control" id="form-last-name">
			                        </div>
			                        <div class="form-group">
			                        	<label class="sr-only" for="form-email">Email</label>
			                        	<input type="email" name="email" placeholder="Email:{{ user.email }}" class="form-email form-control" id="form-email">
		                        </div>
{#			                        <div class="form-group">#}
{#			                        	<label class="sr-only" for="form-about-yourself">个性签名</label>#}
{#			                        	<textarea name="form-about-yourself" placeholder="个性签名"#}
{#			                        				class="form-about-yourself form-control" id="form-about-yourself"></textarea>#}
{#			                        </div>#}
			                        <button type="submit" class="btn">立即修改</button>
			                    </form>
		                    </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>


        <!-- Javascript -->
        <script src="../../../../static/assets1/js/jquery-1.11.1.min.js"></script>
        <script src="../../../../static/assets1/bootstrap/js/bootstrap.min.js"></script>
        <script src="../../../../static/assets1/js/jquery.backstretch.min.js"></script>
        <script src="../../../../static/assets1/js/retina-1.1.0.min.js"></script>
        <script src="../../../../static/assets1/js/scripts.js"></script>

        <!--[if lt IE 10]>
            <script src="../../../../static/assets1/js/placeholder.js"></script>
        <![endif]-->

    </body>

</html>

apps/cms/templates/cms/change_logo.html
{% load staticfiles%}
{% load user_tags %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>修改头像</title>
<link href="../../../../static/Wopop_files/style_log.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="../../../../static/Wopop_files/style.css">
<link rel="stylesheet" type="text/css" href="../../../../static/Wopop_files/userpanel.css">
<link rel="stylesheet" type="text/css" href="../../../../static/Wopop_files/jquery.ui.all.css">

</head>

<body class="login" mycollectionplug="bind">
        {% block script %}
        <script type="text/javascript">
            {% if error_info %}
                xtalert.alertError('{{ error_info }}')
            {% endif %}
            {% if info %}
                 xtalert.alertInfo('{{ info }}')
            {% endif %}
            {% if success_info %}
                 xtalert.alertSuccessToast('{{ success_info }}！');
            {% endif %}
        </script>
        {% endblock %}

    <div class="login_m">
    <div class="login_logo"><img src="../../../../static/Wopop_files/logo.png" width="196" height="46"></div>
        <div class="login_boder">

            <div class="login_padding" id="login_model">
                <form action="{% url 'cms:change_logo' %}" enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="rem_sub">
                        <img src="../media/{{ user.icon }}" alt="头像" style="width: 200px;height: 200px">
                        <input type="file" name="icon">
{#                        <input type="submit" value="更改头像">#}
                        <label>
                          <input type="submit" class="sub_button" name="button" id="button" value="上传头像" style="opacity: 0.7;">
                        </label>
                    </div>
                </form>

            </div>

        </div>
        <div class="collapse navbar-collapse" id="top-navbar-1">
					<ul class="nav navbar-nav navbar-right">
                            <span class="li-text">
								返回：
							</span>
							<a href="{% url 'cms:change_info1' %}"><strong>个人中心</strong></a>
                            <span class="li-text">
								||
							</span>
							<a href="{% url 'cms:index' %}"><strong color="pink">主页</strong></a>
						</li>
					</ul>
				</div>
			</div>
    </div>


</body></html>

apps/cms/templates/cms/index.html
{% extends 'cms/cms_base.html' %}
{% block title %}
后台主页
{% endblock %}
{% block index_navbar_class %}
    class="active"
{% endblock %}

apps/cms/templates/cms/login.html
{% extends 'cms/index1.html' %}
{% block title %}
    登录
{% endblock %}
{#{% block content %}#}
{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_ul }}#}
{#        <input type="submit" value="提交">#}
{#    </form>#}
{#{% endblock %}#}

apps/cms/templates/cms/member-list.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/static/h-ui/css/H-ui.min.css" />
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/static/h-ui.admin/css/H-ui.admin.css" />
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/lib/Hui-iconfont/1.0.8/iconfont.css" />
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/static/h-ui.admin/skin/default/skin.css" id="skin" />
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/static/h-ui.admin/css/style.css" />
<!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<title>用户管理</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> <a href="{% url 'cms:change_info1' %}">首页</a><span class="c-gray en">&gt;</span>个人中心<span class="c-gray en">&gt;</span> 用户管理 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="page-container">

{#		<input type="text" onfocus="WdatePicker({ maxDate:'#F{$dp.$D(\'datemax\')||\'%y-%M-%d\'}' })" id="datemin" class="input-text Wdate" style="width:120px;">#}
{#		-#}
{#		<input type="text" onfocus="WdatePicker({ minDate:'#F{$dp.$D(\'datemin\')}',maxDate:'%y-%M-%d' })" id="datemax" class="input-text Wdate" style="width:120px;">#}
{#		<input type="text" class="input-text" style="width:250px" placeholder="输入会员名称、电话、邮箱" id="" name="">#}
    <button type="submit" class="btn btn-success radius" id="" name=""><a href="{% url 'cms:member_list' %}">搜索全部用户</a></button>
	<div class="cl pd-5 bg-1 bk-gray mt-20"> <span class="l"><a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a> <a href="javascript:;" onclick="member_add('添加用户','member-add.html','','510')" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加用户</a></span> <span class="r">共有数据：<strong>88</strong> 条</span> </div>
	<div class="mt-20">
        <form action="{% url 'cms:member_list' %}" method="post">
        {% csrf_token %}
            <table class="table table-border table-bordered table-hover table-bg table-sort">
                <thead>
                    <tr class="text-c">
                        <th width="25"><input type="checkbox" name="" value=""></th>
                        <th width="80">ID</th>
                        <th width="50" height="50">头像</th>
                        <th width="100">用户名</th>
                        <th width="90">手机</th>
                        <th width="">邮箱</th>
                        <th width="">加入时间</th>
                        <th width="">是否为管理员</th>
                        <th width="">账号操作</th>
                    </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr class="text-c">
                            <td><input type="checkbox" value="1" name=""></td>
                            <td>{{ user.id }}</td>
                            <td><img class="img-circle" style="height: 25px;width: 25px" src="\media\{{ user.icon }}" alt="头像"/></td>
                            <td>{{ user.name }}</td>
                            <td>{{ user.telephone }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.date_join }}</td>
                            <td class="td-status"><span class="label label-success radius">{{ user.is_superuser }}</span></td>
{#                            <td class="td-status">{% if url.is_superuser %}<span class="label label-success radius">管理员</span>{% endif %}</td>#}
                            <td class="td-manage"><a style="text-decoration:none" onClick="member_stop(this,'10001')" href="" title="停用"><i class="Hui-iconfont">&#xe631;</i></a> <a title="编辑" href="javascript:;" onclick="member_edit('编辑','member-add.html','4','','510')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a> <a style="text-decoration:none" class="ml-5" onClick="change_password('修改密码','change-password.html','10001','600','270')" href="javascript:;" title="修改密码"><i class="Hui-iconfont">&#xe63f;</i></a> <a title="删除" href="{% url 'cms:member_warn' %}?id={{ user.id }}" onclick="member_del(this,'1')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>
	</div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="../../../../static/assets2/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="../../../../static/assets2/lib/layer/2.4/layer.js"></script>
<script type="text/javascript" src="../../../../static/assets2/static/h-ui/js/H-ui.min.js"></script>
<script type="text/javascript" src="../../../../static/assets2/static/h-ui.admin/js/H-ui.admin.js"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="../../../../static/assets2/lib/My97DatePicker/4.8/WdatePicker.js"></script>
<script type="text/javascript" src="../../../../static/assets2/lib/datatables/1.10.0/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="../../../../static/assets2/lib/laypage/1.2/laypage.js"></script>
<script type="text/javascript">
$(function(){
	$('.table-sort').dataTable({
		"aaSorting": [[ 1, "desc" ]],//默认第几个排序
		"bStateSave": true,//状态保存
		"aoColumnDefs": [
		  //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
		  {"orderable":false,"aTargets":[0,8,9]}// 制定列不参与排序
		]
	});

});
</script>
</body>
</html>

apps/cms/templates/cms/member_delete.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->
    <link rel="stylesheet" href="../../../../static/CSS/reset.css">
  <link rel="stylesheet" href="../../../../static/CSS/index.css">
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/static/h-ui/css/H-ui.min.css" />
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/static/h-ui.admin/css/H-ui.admin.css" />
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/lib/Hui-iconfont/1.0.8/iconfont.css" />
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/static/h-ui.admin/skin/default/skin.css" id="skin" />
<link rel="stylesheet" type="text/css" href="../../../../static/assets2/static/h-ui.admin/css/style.css" />
<!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<title>用户删除</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> <a href="{% url 'cms:change_info1' %}">首页</a><span class="c-gray en">&gt;</span>个人中心<span class="c-gray en">&gt;</span> 用户管理 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="page-container">

{#		<input type="text" onfocus="WdatePicker({ maxDate:'#F{$dp.$D(\'datemax\')||\'%y-%M-%d\'}' })" id="datemin" class="input-text Wdate" style="width:120px;">#}
{#		-#}
{#		<input type="text" onfocus="WdatePicker({ minDate:'#F{$dp.$D(\'datemin\')}',maxDate:'%y-%M-%d' })" id="datemax" class="input-text Wdate" style="width:120px;">#}
{#		<input type="text" class="input-text" style="width:250px" placeholder="输入会员名称、电话、邮箱" id="" name="">#}
    <button type="submit" class="btn btn-success radius" id="" name=""><a href="{% url 'cms:member_list' %}">搜索全部用户</a></button>
	<div class="cl pd-5 bg-1 bk-gray mt-20"> <span class="l"><a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a> <a href="javascript:;" onclick="member_add('添加用户','member-add.html','','510')" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加用户</a></span> <span class="r">共有数据：<strong>88</strong> 条</span> </div>
	<div class="mt-20">
        <form action="{% url 'cms:member_warn' %}" method="post">
        {% csrf_token %}
            <table class="table table-border table-bordered table-hover table-bg table-sort">
                <thead>
                    <tr class="text-c">
                        <th width="25"><input type="checkbox" name="" value=""></th>
                        <th width="80">ID</th>
                        <th width="50" height="50">头像</th>
                        <th width="100">用户名</th>
                        <th width="90">手机</th>
                        <th width="">邮箱</th>
                        <th width="">加入时间</th>
                        <th width="">是否为管理员</th>
                        <th width="">账号操作</th>
                    </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr class="text-c">
                            <td><input type="checkbox" value="1" name=""></td>
                            <td>{{ user.id }}</td>
                            <td><img class="img-circle" style="height: 25px;width: 25px" src="\media\{{ user.icon }}" alt="头像"/></td>
                            <td>{{ user.name }}</td>
                            <td>{{ user.telephone }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.date_join }}</td>
                            <td class="td-status"><span class="label label-success radius">{{ user.is_superuser }}</span></td>
{#                            <td class="td-status">{% if url.is_superuser %}<span class="label label-success radius">管理员</span>{% endif %}</td>#}
                            <td class="td-manage"><a style="text-decoration:none" onClick="member_stop(this,'10001')" href="" title="停用"><i class="Hui-iconfont">&#xe631;</i></a> <a title="编辑" href="javascript:;" onclick="member_edit('编辑','member-add.html','4','','510')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a> <a style="text-decoration:none" class="ml-5" onClick="change_password('修改密码','change-password.html','10001','600','270')" href="javascript:;" title="修改密码"><i class="Hui-iconfont">&#xe63f;</i></a> <a title="删除" href="{% url 'cms:member_warn' %}?id={{ user.id }}" onclick="member_del(this,'1')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i>[/url] </a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>
	</div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="../../../../static/assets2/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="../../../../static/assets2/lib/layer/2.4/layer.js"></script>
<script type="text/javascript" src="../../../../static/assets2/static/h-ui/js/H-ui.min.js"></script>
<script type="text/javascript" src="../../../../static/assets2/static/h-ui.admin/js/H-ui.admin.js"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="../../../../static/assets2/lib/My97DatePicker/4.8/WdatePicker.js"></script>
<script type="text/javascript" src="../../../../static/assets2/lib/datatables/1.10.0/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="../../../../static/assets2/lib/laypage/1.2/laypage.js"></script>
<script type="text/javascript">
$(function(){
	$('.table-sort').dataTable({
		"aaSorting": [[ 1, "desc" ]],//默认第几个排序
		"bStateSave": true,//状态保存
		"aoColumnDefs": [
		  //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
		  {"orderable":false,"aTargets":[0,8,9]}// 制定列不参与排序
		]
	});

});
</script>
<script src="http://www.jq22.com/jquery/jquery-1.10.2.js"></script>
  <script src="../../../../static/JS/script.js"></script>
</body>
</html>

apps/cms/templates/cms/register.html
{% extends 'cms/index1.html' %}
{% block title %}
    注册
{% endblock %}
{#{% block content %}#}
{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_ul }}#}
{#        <input type="submit" value="提交">#}
{#    </form>#}
{#{% endblock %}#}